services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5100:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14.5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
    db-data:
        driver: local
